#!/usr/bin/env python

# Copyright 2024 Columbia Artificial Intelligence, Robotics Lab,
# and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Diffusion Policy as per "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion"

TODO(alexander-soare):
  - Remove reliance on diffusers for DDPMScheduler and LR scheduler.
"""

import math
from collections import deque
from collections.abc import Callable

import einops
import numpy as np
import torch
import torch.nn.functional as F  # noqa: N812
import torchvision
from diffusers.schedulers.scheduling_ddim import DDIMScheduler
from diffusers.schedulers.scheduling_ddpm import DDPMScheduler
from torch import Tensor, nn

from lerobot.policies.diffusion.configuration_diffusion import DiffusionConfig
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import (
    get_device_from_parameters,
    get_dtype_from_parameters,
    get_output_shape,
    populate_queues,
)
from lerobot.utils.constants import ACTION, OBS_ENV_STATE, OBS_IMAGES, OBS_STATE


class DiffusionPolicy(PreTrainedPolicy):
    """
    Diffusion Policy as per "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion"
    (paper: https://huggingface.co/papers/2303.04137, code: https://github.com/real-stanford/diffusion_policy).
    """

    config_class = DiffusionConfig
    name = "diffusion"

    def __init__(
        self,
        config: DiffusionConfig,
        **kwargs,
    ):
        """
        Args:
            config: Policy configuration class instance or None, in which case the default instantiation of
                the configuration class is used.
            dataset_stats: Dataset statistics to be used for normalization. If not passed here, it is expected
                that they will be passed with a call to `load_state_dict` before the policy is used.
        """
        super().__init__(config)
        config.validate_features()
        self.config = config

        # queues are populated during rollout of the policy, they contain the n latest observations and actions
        self._queues = None

        self.diffusion = DiffusionModel(config)

        self.reset()

    def get_optim_params(self) -> dict:
        return self.diffusion.parameters()

    def reset(self):
        """Clear observation and action queues. Should be called on `env.reset()`"""
        self._queues = {
            OBS_STATE: deque(maxlen=self.config.n_obs_steps),
            ACTION: deque(maxlen=self.config.n_action_steps),
        }
        if self.config.image_features:
            self._queues[OBS_IMAGES] = deque(maxlen=self.config.n_obs_steps)
        if self.config.env_state_feature:
            self._queues[OBS_ENV_STATE] = deque(maxlen=self.config.n_obs_steps)
        if self.config.model in {"scene_only", "robot_scene"}:
            self._queues[self.config.future_ball_pos_key] = deque(maxlen=self.config.n_obs_steps)
        if self.config.enable_kalman_condition or self.config.model != "orig":
            self._queues["timestamp"] = deque(maxlen=self.config.n_obs_steps)

    @torch.no_grad()
    def predict_action_chunk(self, batch: dict[str, Tensor], noise: Tensor | None = None) -> Tensor:
        """Predict a chunk of actions given environment observations."""
        # stack n latest observations from the queue
        batch = {k: torch.stack(list(self._queues[k]), dim=1) for k in batch if k in self._queues}
        actions = self.diffusion.generate_actions(batch, noise=noise)

        return actions

    @torch.no_grad()
    def select_action(self, batch: dict[str, Tensor], noise: Tensor | None = None) -> Tensor:
        """Select a single action given environment observations.

        This method handles caching a history of observations and an action trajectory generated by the
        underlying diffusion model. Here's how it works:
          - `n_obs_steps` steps worth of observations are cached (for the first steps, the observation is
            copied `n_obs_steps` times to fill the cache).
          - The diffusion model generates `horizon` steps worth of actions.
          - `n_action_steps` worth of actions are actually kept for execution, starting from the current step.
        Schematically this looks like:
            ----------------------------------------------------------------------------------------------
            (legend: o = n_obs_steps, h = horizon, a = n_action_steps)
            |timestep            | n-o+1 | n-o+2 | ..... | n     | ..... | n+a-1 | n+a   | ..... | n-o+h |
            |observation is used | YES   | YES   | YES   | YES   | NO    | NO    | NO    | NO    | NO    |
            |action is generated | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   |
            |action is used      | NO    | NO    | NO    | YES   | YES   | YES   | NO    | NO    | NO    |
            ----------------------------------------------------------------------------------------------
        Note that this means we require: `n_action_steps <= horizon - n_obs_steps + 1`. Also, note that
        "horizon" may not the best name to describe what the variable actually means, because this period is
        actually measured from the first observation which (if `n_obs_steps` > 1) happened in the past.
        """
        # NOTE: for offline evaluation, we have action in the batch, so we need to pop it out
        if ACTION in batch:
            batch.pop(ACTION)

        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        # NOTE: It's important that this happens after stacking the images into a single key.
        self._queues = populate_queues(self._queues, batch)

        if len(self._queues[ACTION]) == 0:
            actions = self.predict_action_chunk(batch, noise=noise)
            self._queues[ACTION].extend(actions.transpose(0, 1))

        action = self._queues[ACTION].popleft()
        return action

    def forward(self, batch: dict[str, Tensor]) -> tuple[Tensor, None]:
        """Run the batch through the model and compute the loss for training or validation."""
        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            for key in self.config.image_features:
                if self.config.n_obs_steps == 1 and batch[key].ndim == 4:
                    batch[key] = batch[key].unsqueeze(1)
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        loss = self.diffusion.compute_loss(batch)
        # no output_dict so returning None
        return loss, None


def _make_noise_scheduler(name: str, **kwargs: dict) -> DDPMScheduler | DDIMScheduler:
    """
    Factory for noise scheduler instances of the requested type. All kwargs are passed
    to the scheduler.
    """
    if name == "DDPM":
        return DDPMScheduler(**kwargs)
    elif name == "DDIM":
        return DDIMScheduler(**kwargs)
    else:
        raise ValueError(f"Unsupported noise scheduler type {name}")


class DiffusionModel(nn.Module):
    @staticmethod
    def _kalman_feature_dim(mode: str) -> int:
        dims = {"full10": 10, "posvel6": 6, "vel3": 3, "velpred6": 6, "pred3": 3}
        if mode not in dims:
            raise ValueError(f"Unsupported kalman_feature_mode: {mode}")
        return dims[mode]

    def __init__(self, config: DiffusionConfig):
        super().__init__()
        self.config = config
        self._use_env_state_as_future_mask = self.config.use_env_state_to_mask_future
        if self.config.use_labels_environment_state or self._use_env_state_as_future_mask:
            if self.config.input_features is None or OBS_ENV_STATE not in self.config.input_features:
                raise ValueError(
                    "Labels-backed environment_state requires "
                    f"`{OBS_ENV_STATE}` to be present in policy input_features."
                )
            env_feature_keys = [
                key for key, feature in self.config.input_features.items() if feature.type.value == "ENV"
            ]
            if env_feature_keys != [OBS_ENV_STATE]:
                raise ValueError(
                    "Labels-backed environment_state requires the ENV input feature set to be exactly "
                    f"[`{OBS_ENV_STATE}`]. Got {env_feature_keys}."
                )
            env_state_shape = tuple(self.config.input_features[OBS_ENV_STATE].shape)
            if self._use_env_state_as_future_mask and (len(env_state_shape) != 1 or env_state_shape[0] != 1):
                raise ValueError(
                    "`use_env_state_to_mask_future=True` requires "
                    f"`{OBS_ENV_STATE}` to have shape (1,). Got {self.config.input_features[OBS_ENV_STATE].shape}."
                )
        self._kalman_pos_slice = self._parse_kalman_pos_slice(self.config.kalman_state_pos_slice)
        self._kalman_raw_dim = 0
        self._kalman_cond_dim = 0
        self.kalman_feature_mlp: nn.Module | None = None
        self.kalman_feature_gate: nn.Module | None = None
        self._future_mode = self.config.model
        self._use_future_robot_state = self._future_mode in {"robot_only", "robot_scene"}
        self._use_future_ball_pos = self._future_mode in {"scene_only", "robot_scene"}
        self._disable_future_condition_gate = self.config.disable_future_condition_gate
        self._future_delay_deltas = tuple(int(d) for d in self.config.future_condition_deltas)
        self._future_delay_count = len(self._future_delay_deltas)
        self._future_delay_index_by_delta = {delta: i for i, delta in enumerate(self._future_delay_deltas)}
        self._delay_random_active = (
            self.config.model != "orig" and self.config.delay_random and self._future_delay_count > 1
        )
        self._delay_random_probs = None
        if self._delay_random_active:
            probs = torch.tensor(self.config.delay_random_probs, dtype=torch.float32)
            self._delay_random_probs = probs / probs.sum()
        self._future_state_cond_dim = 0
        self._future_ball_pos_in_dim = 0
        self._future_ball_pos_cond_dim = 0
        self.future_state_gate: nn.Module | None = None
        self.future_ball_pos_mlp: nn.Module | None = None
        self.future_ball_pos_gate: nn.Module | None = None
        self._last_future_gate_debug: dict[str, list[float]] | None = None
        self._history_gate_context_dim = 0

        # Build observation encoders (depending on which observations are provided).
        non_kalman_global_cond_dim = self.config.robot_state_feature.shape[0]
        if self.config.image_features:
            num_images = len(self.config.image_features)
            if self.config.use_separate_rgb_encoder_per_camera:
                encoders = [DiffusionRgbEncoder(config) for _ in range(num_images)]
                self.rgb_encoder = nn.ModuleList(encoders)
                non_kalman_global_cond_dim += encoders[0].feature_dim * num_images
            else:
                self.rgb_encoder = DiffusionRgbEncoder(config)
                non_kalman_global_cond_dim += self.rgb_encoder.feature_dim * num_images
        if self.config.env_state_feature and not self._use_env_state_as_future_mask:
            non_kalman_global_cond_dim += self.config.env_state_feature.shape[0]
        self._history_gate_context_dim = non_kalman_global_cond_dim * config.n_obs_steps

        kalman_cond_dim = 0
        if self.config.enable_kalman_condition:
            self._kalman_raw_dim = self._kalman_feature_dim(self.config.kalman_feature_mode)
            self._kalman_cond_dim = (
                self.config.kalman_feature_mlp_dim
                if self.config.enable_kalman_feature_mlp and self.config.kalman_feature_mlp_dim is not None
                else self._kalman_raw_dim
            )
            kalman_cond_dim = self._kalman_cond_dim
            if self.config.enable_kalman_feature_mlp:
                self.kalman_feature_mlp = nn.Sequential(
                    nn.Linear(self._kalman_raw_dim, self._kalman_cond_dim),
                    nn.SiLU(),
                    nn.Linear(self._kalman_cond_dim, self._kalman_cond_dim),
                )
            if self.config.enable_kalman_feature_gate:
                self.kalman_feature_gate = nn.Sequential(
                    nn.Linear(self._kalman_cond_dim, self._kalman_cond_dim),
                    nn.Sigmoid(),
                )
        future_cond_dim = 0
        if self._use_future_robot_state:
            self._future_state_cond_dim = self.config.robot_state_feature.shape[0]
            future_cond_dim += self._future_state_cond_dim
            if not self._disable_future_condition_gate:
                future_state_gate_in_dim = self._future_state_cond_dim
                if self.config.use_history4gate:
                    future_state_gate_in_dim += self._history_gate_context_dim
                self.future_state_gate = nn.Sequential(
                    nn.Linear(future_state_gate_in_dim, self._future_state_cond_dim),
                    nn.Sigmoid(),
                )
        if self._use_future_ball_pos:
            if self.config.input_features is None or self.config.future_ball_pos_key not in self.config.input_features:
                raise ValueError(
                    f"Missing required input feature `{self.config.future_ball_pos_key}` for {self._future_mode}."
                )
            self._future_ball_pos_in_dim = math.prod(self.config.input_features[self.config.future_ball_pos_key].shape)
            self._future_ball_pos_cond_dim = self.config.future_ball_pos_mlp_dim
            future_cond_dim += self._future_ball_pos_cond_dim
            self.future_ball_pos_mlp = nn.Sequential(
                nn.Linear(self._future_ball_pos_in_dim, self._future_ball_pos_cond_dim),
                nn.SiLU(),
                nn.Linear(self._future_ball_pos_cond_dim, self._future_ball_pos_cond_dim),
            )
            if not self._disable_future_condition_gate:
                future_ball_gate_in_dim = self._future_ball_pos_cond_dim
                if self.config.use_history4gate:
                    future_ball_gate_in_dim += self._history_gate_context_dim
                self.future_ball_pos_gate = nn.Sequential(
                    nn.Linear(future_ball_gate_in_dim, self._future_ball_pos_cond_dim),
                    nn.Sigmoid(),
                )

        full_global_cond_dim = non_kalman_global_cond_dim + kalman_cond_dim
        non_kalman_global_cond_dim_flat = non_kalman_global_cond_dim * config.n_obs_steps + future_cond_dim
        full_global_cond_dim_flat = full_global_cond_dim * config.n_obs_steps + future_cond_dim
        if self.config.enable_kalman_condition and self.config.enable_kalman_mid_only_condition:
            self.unet = DiffusionConditionalUnet1d(
                config,
                global_cond_dim=non_kalman_global_cond_dim_flat,
                global_cond_mid_dim=full_global_cond_dim_flat,
            )
        else:
            self.unet = DiffusionConditionalUnet1d(
                config,
                global_cond_dim=full_global_cond_dim_flat,
            )

        if config.compile_model:
            # Compile the U-Net. "reduce-overhead" is preferred for the small-batch repetitive loops
            # common in diffusion inference.
            self.unet = torch.compile(self.unet, mode=config.compile_mode)

        self.noise_scheduler = _make_noise_scheduler(
            config.noise_scheduler_type,
            num_train_timesteps=config.num_train_timesteps,
            beta_start=config.beta_start,
            beta_end=config.beta_end,
            beta_schedule=config.beta_schedule,
            clip_sample=config.clip_sample,
            clip_sample_range=config.clip_sample_range,
            prediction_type=config.prediction_type,
        )

        if config.num_inference_steps is None:
            self.num_inference_steps = self.noise_scheduler.config.num_train_timesteps
        else:
            self.num_inference_steps = config.num_inference_steps

    @staticmethod
    def _parse_kalman_pos_slice(spec: str) -> slice:
        parts = spec.split(":")
        if len(parts) != 2:
            raise ValueError(f"Invalid kalman position slice: {spec}")
        start = int(parts[0]) if parts[0] else None
        end = int(parts[1]) if parts[1] else None
        return slice(start, end)

    def _resolve_kalman_dt(
        self,
        batch: dict[str, Tensor],
        batch_size: int,
        n_steps: int,
        *,
        device: torch.device,
        dtype: torch.dtype,
    ) -> Tensor:
        dt = torch.full((batch_size, n_steps), float(self.config.kalman_dt_fallback), device=device, dtype=dtype)
        if "timestamp" not in batch:
            return dt

        ts = batch["timestamp"]
        if ts.ndim == 1:
            ts = ts.unsqueeze(1)
        elif ts.ndim >= 3 and ts.shape[-1] == 1:
            ts = ts.squeeze(-1)
        if ts.ndim < 2 or ts.shape[0] != batch_size or ts.shape[1] < n_steps:
            return dt

        ts = ts[:, :n_steps].to(device=device, dtype=dtype)
        dt[:, 1:] = ts[:, 1:] - ts[:, :-1]
        dt = torch.where(
            (dt > 0) & torch.isfinite(dt),
            dt,
            torch.full_like(dt, float(self.config.kalman_dt_fallback)),
        )
        return dt

    def _select_future_delay_indices(self, batch_size: int, device: torch.device) -> Tensor:
        if self._delay_random_active and self.training:
            if self._delay_random_probs is None:
                raise RuntimeError("delay_random is enabled but delay_random_probs are not initialized.")
            return torch.multinomial(self._delay_random_probs.to(device=device), batch_size, replacement=True)

        fixed_delta = int(self.config.future_condition_delta)
        fixed_idx = self._future_delay_index_by_delta.get(fixed_delta)
        if fixed_idx is None:
            raise ValueError(
                "`future_condition_delta` is not present in active future delta candidates. "
                f"Got {fixed_delta}, candidates: {self._future_delay_deltas}."
            )
        return torch.full((batch_size,), fixed_idx, device=device, dtype=torch.long)

    def _future_delay_steps_from_indices(
        self,
        delay_indices: Tensor,
        *,
        device: torch.device,
        dtype: torch.dtype,
    ) -> Tensor:
        delay_values = torch.tensor(self._future_delay_deltas, device=device, dtype=dtype)
        return delay_values[delay_indices]

    def _maybe_apply_future_gate(self, cond: Tensor, gate: nn.Module | None, *, gate_name: str) -> Tensor:
        if self._disable_future_condition_gate:
            return cond
        if gate is None:
            raise RuntimeError(f"{gate_name} is not initialized.")
        return cond * gate(cond)

    def _apply_future_gate_with_debug(
        self,
        cond: Tensor,
        gate: nn.Module | None,
        *,
        gate_name: str,
        history_context: Tensor | None = None,
    ) -> tuple[Tensor, Tensor | None]:
        if self._disable_future_condition_gate:
            return cond, None
        if gate is None:
            raise RuntimeError(f"{gate_name} is not initialized.")
        gate_input = cond
        if self.config.use_history4gate:
            if history_context is None:
                raise RuntimeError(f"{gate_name} requires history_context when use_history4gate=True.")
            gate_input = torch.cat([cond, history_context], dim=-1)
        gate_values = gate(gate_input)
        return cond * gate_values, gate_values

    def _select_future_from_explicit_sequence(
        self,
        future_obs: Tensor,
        delay_indices: Tensor,
        *,
        branch_name: str,
    ) -> Tensor:
        if future_obs.ndim == 2:
            return future_obs
        if future_obs.ndim != 3:
            raise ValueError(
                f"Explicit future {branch_name} must have shape (B, S, D) or (B, D). Got {tuple(future_obs.shape)}."
            )
        if future_obs.shape[1] == 0:
            raise ValueError(f"Explicit future {branch_name} has zero sequence length.")
        if future_obs.shape[1] == 1:
            return future_obs[:, 0]
        if future_obs.shape[1] != self._future_delay_count:
            raise ValueError(
                f"Explicit future {branch_name} sequence length mismatch. "
                f"Expected {self._future_delay_count} from deltas {self._future_delay_deltas}, "
                f"got {future_obs.shape[1]}."
            )
        gather_idx = delay_indices.view(-1, 1, 1).expand(-1, 1, future_obs.shape[-1])
        return future_obs.gather(1, gather_idx).squeeze(1)

    def _predict_future_observation_with_kalman(
        self,
        obs_history: Tensor,
        batch: dict[str, Tensor],
        future_steps: Tensor | int | float | None = None,
    ) -> Tensor:
        """
        Predict future observation at `future_condition_delta` steps ahead from history using
        per-dimension constant-velocity Kalman filtering.

        Args:
            obs_history: (B, S, D) observation history (already normalized like policy inputs).
            batch: Input batch, optionally containing `timestamp` with shape (B, S).
        Returns:
            Tensor with shape (B, D): predicted future observation.
        """
        if obs_history.ndim != 3:
            raise ValueError(f"Expected obs history to have shape (B, S, D), got {tuple(obs_history.shape)}.")

        b, s, d = obs_history.shape
        device = obs_history.device
        dtype = obs_history.dtype

        valid = torch.isfinite(obs_history)
        z = torch.nan_to_num(obs_history, nan=0.0, posinf=0.0, neginf=0.0)
        dt = self._resolve_kalman_dt(batch, b, s, device=device, dtype=dtype)

        # Flatten batch and feature dims so we can run one scalar Kalman per dimension.
        n = b * d
        x = torch.zeros((n, 2), device=device, dtype=dtype)
        x[:, 0] = z[:, 0, :].reshape(-1)
        p = torch.zeros((n, 2, 2), device=device, dtype=dtype)
        p[:, 0, 0] = float(self.config.kalman_init_pos_std**2)
        p[:, 1, 1] = float(self.config.kalman_init_vel_std**2)

        sigma2 = float(self.config.kalman_accel_noise_std**2)
        meas_var = float(self.config.kalman_meas_noise_std**2)
        eps = torch.tensor(1e-12, device=device, dtype=dtype)

        for si in range(s):
            if si > 0:
                step_dt = dt[:, si].unsqueeze(1).expand(b, d).reshape(-1)
                dt2 = step_dt.square()
                dt3 = dt2 * step_dt
                dt4 = dt2.square()

                x0, x1 = x[:, 0], x[:, 1]
                x_pred0 = x0 + step_dt * x1
                x_pred1 = x1
                x = torch.stack([x_pred0, x_pred1], dim=-1)

                p00, p01 = p[:, 0, 0], p[:, 0, 1]
                p10, p11 = p[:, 1, 0], p[:, 1, 1]
                p00_new = p00 + step_dt * (p10 + p01) + dt2 * p11 + (dt4 / 4.0) * sigma2
                p01_new = p01 + step_dt * p11 + (dt3 / 2.0) * sigma2
                p10_new = p10 + step_dt * p11 + (dt3 / 2.0) * sigma2
                p11_new = p11 + dt2 * sigma2
                p[:, 0, 0] = p00_new
                p[:, 0, 1] = p01_new
                p[:, 1, 0] = p10_new
                p[:, 1, 1] = p11_new

            z_si = z[:, si, :].reshape(-1)
            valid_si = valid[:, si, :].reshape(-1)
            if bool(valid_si.any()):
                p00, p01 = p[:, 0, 0], p[:, 0, 1]
                p10, p11 = p[:, 1, 0], p[:, 1, 1]
                y = z_si - x[:, 0]
                s_innov = torch.maximum(p00 + meas_var, eps)
                k0 = p00 / s_innov
                k1 = p10 / s_innov

                x_upd0 = x[:, 0] + k0 * y
                x_upd1 = x[:, 1] + k1 * y
                p00_upd = (1.0 - k0) * p00
                p01_upd = (1.0 - k0) * p01
                p10_upd = p10 - k1 * p00
                p11_upd = p11 - k1 * p01

                x[:, 0] = torch.where(valid_si, x_upd0, x[:, 0])
                x[:, 1] = torch.where(valid_si, x_upd1, x[:, 1])
                p[:, 0, 0] = torch.where(valid_si, p00_upd, p[:, 0, 0])
                p[:, 0, 1] = torch.where(valid_si, p01_upd, p[:, 0, 1])
                p[:, 1, 0] = torch.where(valid_si, p10_upd, p[:, 1, 0])
                p[:, 1, 1] = torch.where(valid_si, p11_upd, p[:, 1, 1])

        if future_steps is None:
            future_steps_tensor = torch.full(
                (b,), float(self.config.future_condition_delta), device=device, dtype=dtype
            )
        elif isinstance(future_steps, Tensor):
            if future_steps.ndim != 1 or future_steps.shape[0] != b:
                raise ValueError(
                    f"`future_steps` tensor must have shape ({b},). Got {tuple(future_steps.shape)}."
                )
            future_steps_tensor = future_steps.to(device=device, dtype=dtype)
        else:
            future_steps_tensor = torch.full((b,), float(future_steps), device=device, dtype=dtype)

        horizon_dt = dt[:, -1] * future_steps_tensor
        horizon_dt = horizon_dt.unsqueeze(1).expand(b, d).reshape(-1)
        pred = x[:, 0] + horizon_dt * x[:, 1]
        return pred.view(b, d)

    def _split_state_sequence(self, state_obs: Tensor) -> tuple[Tensor, Tensor | None]:
        if state_obs.ndim != 3:
            raise ValueError(f"`{OBS_STATE}` must have shape (B, S, D). Got {tuple(state_obs.shape)}.")
        if state_obs.shape[1] < self.config.n_obs_steps:
            raise ValueError(
                f"`{OBS_STATE}` must contain at least {self.config.n_obs_steps} steps. "
                f"Got shape {tuple(state_obs.shape)}."
            )

        state_history = state_obs[:, : self.config.n_obs_steps]
        future_state = None
        if self._use_future_robot_state and state_obs.shape[1] > self.config.n_obs_steps:
            future_state = state_obs[:, self.config.n_obs_steps :]
        return state_history, future_state

    def _prepare_future_conditioning(
        self,
        batch: dict[str, Tensor],
        batch_size: int,
        dtype: torch.dtype,
        device: torch.device,
        state_history_obs: Tensor,
        future_state_obs: Tensor | None,
        history_gate_context: Tensor | None = None,
        future_keep_mask: Tensor | None = None,
    ) -> Tensor | None:
        future_parts: list[Tensor] = []
        future_gate_debug: dict[str, Tensor] = {}
        future_delay_indices = self._select_future_delay_indices(batch_size, device=device)
        future_delay_steps = self._future_delay_steps_from_indices(
            future_delay_indices, device=device, dtype=dtype
        )

        if self._use_future_robot_state:
            use_explicit_future_state = future_state_obs is not None and not self.config.use_kalman_future
            if use_explicit_future_state:
                state_future = self._select_future_from_explicit_sequence(
                    future_state_obs, future_delay_indices, branch_name="state"
                )
                state_cond = state_future.reshape(batch_size, -1).to(device=device, dtype=dtype)
            else:
                if self.training and not self.config.use_kalman_future:
                    raise ValueError(
                        "Training requires explicit future state from the dataset when "
                        "`use_kalman_future=False`."
                    )
                # Online eval path or Kalman-future path: predict the future state from history.
                state_cond = self._predict_future_observation_with_kalman(
                    state_history_obs, batch, future_steps=future_delay_steps
                ).to(
                    device=device, dtype=dtype
                )
            if state_cond.shape[-1] != self._future_state_cond_dim:
                raise ValueError(
                    f"Future state dim mismatch. Expected {self._future_state_cond_dim}, got {state_cond.shape[-1]}."
                )
            state_cond, state_gate = self._apply_future_gate_with_debug(
                state_cond,
                self.future_state_gate,
                gate_name="future_state_gate",
                history_context=history_gate_context,
            )
            if state_gate is not None:
                future_gate_debug["future_state_gate_mean"] = state_gate.mean(dim=-1)
            future_parts.append(state_cond)

        if self._use_future_ball_pos:
            if self.future_ball_pos_mlp is None:
                raise RuntimeError("future_ball_pos_mlp is not initialized.")

            ball_future: Tensor | None = None
            ball_history: Tensor | None = None
            ball_future_seq: Tensor | None = None
            if self.config.use_kalman_future and self.config.future_ball_pos_key not in batch:
                raise ValueError(
                    "Kalman future-conditioning for scene branches requires history observations for "
                    f"`{self.config.future_ball_pos_key}` in the batch. "
                    f"Batch keys: {sorted(batch.keys())}."
                )
            if self.config.future_ball_pos_key in batch:
                ball_obs = batch[self.config.future_ball_pos_key]
                if ball_obs.ndim == 2:
                    ball_obs = ball_obs.unsqueeze(1)
                if ball_obs.ndim < 3:
                    raise ValueError(
                        f"`{self.config.future_ball_pos_key}` must have shape (B, S, D). "
                        f"Got {tuple(ball_obs.shape)}."
                    )
                seq_len = ball_obs.shape[1]

                if self.config.use_kalman_future:
                    ball_history = ball_obs[:, : min(seq_len, self.config.n_obs_steps)]
                else:
                    if seq_len == self._future_delay_count:
                        # Offline dataset path for scene_only/robot_scene: explicit future candidates only.
                        ball_future_seq = ball_obs
                    elif seq_len > self.config.n_obs_steps:
                        ball_history = ball_obs[:, : self.config.n_obs_steps]
                        ball_future_seq = ball_obs[:, self.config.n_obs_steps :]
                    else:
                        # Online eval path: only history is available in the observation queue.
                        ball_history = ball_obs[:, : min(seq_len, self.config.n_obs_steps)]

                if (
                    not self.config.use_kalman_future
                    and ball_future_seq is not None
                    and ball_future_seq.shape[1] > 0
                ):
                    ball_future = self._select_future_from_explicit_sequence(
                        ball_future_seq, future_delay_indices, branch_name=self.config.future_ball_pos_key
                    )

                if ball_future is None and ball_history is not None and ball_history.shape[1] > 0:
                    ball_future = self._predict_future_observation_with_kalman(
                        ball_history, batch, future_steps=future_delay_steps
                    )

                if ball_future is not None:
                    ball_future = ball_future.reshape(batch_size, -1).to(device=device, dtype=dtype)
                    if ball_future.shape[-1] != self._future_ball_pos_in_dim:
                        raise ValueError(
                            "Future ball_pos dim mismatch. "
                            f"Expected {self._future_ball_pos_in_dim}, got {ball_future.shape[-1]}."
                        )

            # In training we require explicit future ball_pos from dataset unless Kalman-future is enabled.
            if self.training and not self.config.use_kalman_future:
                if self.config.future_ball_pos_key not in batch:
                    raise ValueError(
                        "Missing required dataset feature for training: "
                        f"`{self.config.future_ball_pos_key}`. "
                        f"Batch keys: {sorted(batch.keys())}."
                    )
                if ball_future_seq is None:
                    ball_obs_shape = (
                        tuple(batch[self.config.future_ball_pos_key].shape)
                        if self.config.future_ball_pos_key in batch
                        else None
                    )
                    raise ValueError(
                        "Training requires explicit future ball_pos from dataset, but got no explicit "
                        "future sequence. Fallback (history/Kalman/zeros) is disabled. "
                        f"`{self.config.future_ball_pos_key}` shape={ball_obs_shape}, "
                        f"expected future candidates={self._future_delay_count}."
                    )

            if self.config.use_kalman_future and ball_future is None:
                raise ValueError(
                    "Kalman future-conditioning for scene branches could not produce a future value from "
                    f"`{self.config.future_ball_pos_key}` history."
                )

            if ball_future is None:
                ball_cond = torch.zeros(
                    (batch_size, self._future_ball_pos_cond_dim),
                    device=device,
                    dtype=dtype,
                )
            else:
                ball_cond = self.future_ball_pos_mlp(ball_future)
                ball_cond, ball_gate = self._apply_future_gate_with_debug(
                    ball_cond,
                    self.future_ball_pos_gate,
                    gate_name="future_ball_pos_gate",
                    history_context=history_gate_context,
                )
                if ball_gate is not None:
                    future_gate_debug["future_ball_pos_gate_mean"] = ball_gate.mean(dim=-1)
                    # Backward-compatible alias used by existing probe/eval scripts.
                    future_gate_debug["future_ball_gate_mean"] = ball_gate.mean(dim=-1)

            future_parts.append(ball_cond)

        if future_gate_debug:
            self._last_future_gate_debug = {
                key: tensor.detach().to(device="cpu", dtype=torch.float32).tolist()
                for key, tensor in future_gate_debug.items()
            }
        else:
            self._last_future_gate_debug = None

        if not future_parts:
            return None
        future_cond = torch.cat(future_parts, dim=-1)
        if future_keep_mask is not None:
            future_cond = future_cond * future_keep_mask.to(device=device, dtype=dtype)
        return future_cond

    def _compute_future_keep_mask_from_env_state(
        self,
        env_state_obs: Tensor,
        n_obs_steps: int,
        dtype: torch.dtype,
    ) -> Tensor:
        if env_state_obs.ndim != 3:
            raise ValueError(
                f"`{OBS_ENV_STATE}` must have shape (B, S, D) when `use_env_state_to_mask_future=True`. "
                f"Got {tuple(env_state_obs.shape)}."
            )
        if env_state_obs.shape[-1] != 1:
            raise ValueError(
                f"`{OBS_ENV_STATE}` must have last dimension 1 when `use_env_state_to_mask_future=True`. "
                f"Got {tuple(env_state_obs.shape)}."
            )
        latest_env_state = env_state_obs[:, n_obs_steps - 1, 0]
        is_binary = torch.logical_or(latest_env_state == 0, latest_env_state == 1)
        if not bool(is_binary.all().item()):
            raise ValueError(
                f"`{OBS_ENV_STATE}` latest history step must be binary 0/1 when "
                "`use_env_state_to_mask_future=True`."
            )
        return (latest_env_state == 0).to(dtype=dtype).unsqueeze(-1)

    def get_last_future_gate_debug(self, clear: bool = False) -> dict[str, list[float]] | None:
        if self._last_future_gate_debug is None:
            return None
        debug = {key: list(values) for key, values in self._last_future_gate_debug.items()}
        if clear:
            self._last_future_gate_debug = None
        return debug

    # ========= inference  ============
    def conditional_sample(
        self,
        batch_size: int,
        global_cond: Tensor | None = None,
        global_cond_mid: Tensor | None = None,
        generator: torch.Generator | None = None,
        noise: Tensor | None = None,
    ) -> Tensor:
        device = get_device_from_parameters(self)
        dtype = get_dtype_from_parameters(self)

        # Sample prior.
        sample = (
            noise
            if noise is not None
            else torch.randn(
                size=(batch_size, self.config.horizon, self.config.action_feature.shape[0]),
                dtype=dtype,
                device=device,
                generator=generator,
            )
        )

        self.noise_scheduler.set_timesteps(self.num_inference_steps)

        for t in self.noise_scheduler.timesteps:
            # Predict model output.
            model_output = self.unet(
                sample,
                torch.full(sample.shape[:1], t, dtype=torch.long, device=sample.device),
                global_cond=global_cond,
                global_cond_mid=global_cond_mid,
            )
            # Compute previous image: x_t -> x_t-1
            sample = self.noise_scheduler.step(model_output, t, sample, generator=generator).prev_sample

        return sample

    def _prepare_unet_conditioning(self, batch: dict[str, Tensor]) -> tuple[Tensor, Tensor | None]:
        """
        Prepare conditioning tensors.

        Returns:
            (global_cond, global_cond_mid)
            - default path: (full_cond, None)
            - kalman mid-only path: (non_kalman_cond, full_cond)
        """
        state_obs, future_state_obs = self._split_state_sequence(batch[OBS_STATE])
        batch_size, n_obs_steps = state_obs.shape[:2]
        non_kalman_feats = [state_obs]

        # Extract image features.
        if self.config.image_features:
            obs_images = batch[OBS_IMAGES][:, :n_obs_steps]
            if self.config.use_separate_rgb_encoder_per_camera:
                # Combine batch and sequence dims while rearranging to make the camera index dimension first.
                images_per_camera = einops.rearrange(obs_images, "b s n ... -> n (b s) ...")
                img_features_list = torch.cat(
                    [
                        encoder(images)
                        for encoder, images in zip(self.rgb_encoder, images_per_camera, strict=True)
                    ]
                )
                # Separate batch and sequence dims back out. The camera index dim gets absorbed into the
                # feature dim (effectively concatenating the camera features).
                img_features = einops.rearrange(
                    img_features_list, "(n b s) ... -> b s (n ...)", b=batch_size, s=n_obs_steps
                )
            else:
                # Combine batch, sequence, and "which camera" dims before passing to shared encoder.
                img_features = self.rgb_encoder(
                    einops.rearrange(obs_images, "b s n ... -> (b s n) ...")
                )
                # Separate batch dim and sequence dim back out. The camera index dim gets absorbed into the
                # feature dim (effectively concatenating the camera features).
                img_features = einops.rearrange(
                    img_features, "(b s n) ... -> b s (n ...)", b=batch_size, s=n_obs_steps
                )
            non_kalman_feats.append(img_features)

        kalman_features: Tensor | None = None
        if self.config.enable_kalman_condition:
            kalman_features = self._compute_online_kalman_from_state(batch)
            if self.kalman_feature_mlp is not None:
                kalman_features = self.kalman_feature_mlp(kalman_features)
            if self.kalman_feature_gate is not None:
                kalman_features = kalman_features * self.kalman_feature_gate(kalman_features)
            # Force-zero is defined on the final tensor that is injected into U-Net conditioning.
            if self.config.kalman_force_zero_global_condition:
                kalman_features = torch.zeros(
                    (batch_size, n_obs_steps, self._kalman_cond_dim),
                    device=state_obs.device,
                    dtype=state_obs.dtype,
                )

        if (self.config.use_labels_environment_state or self._use_env_state_as_future_mask) and OBS_ENV_STATE not in batch:
            raise ValueError(
                "Labels-backed environment_state requires "
                f"`{OBS_ENV_STATE}` in every training batch. Batch keys: {sorted(batch.keys())}."
            )

        future_keep_mask: Tensor | None = None
        if self.config.env_state_feature:
            env_state_obs = batch[OBS_ENV_STATE]
            if env_state_obs.shape[1] < n_obs_steps:
                raise ValueError(
                    f"`{OBS_ENV_STATE}` must contain at least {n_obs_steps} steps. "
                    f"Got shape {tuple(env_state_obs.shape)}."
                )
            expected_env_dim = self.config.input_features[OBS_ENV_STATE].shape[0]
            if env_state_obs.shape[-1] != expected_env_dim:
                raise ValueError(
                    f"`{OBS_ENV_STATE}` last dimension must match configured shape {expected_env_dim}. "
                    f"Got shape {tuple(env_state_obs.shape)}."
                )
            if not torch.isfinite(env_state_obs[:, :n_obs_steps]).all():
                raise ValueError(
                    f"`{OBS_ENV_STATE}` contains non-finite values in the first {n_obs_steps} history steps."
                )
            if self._use_env_state_as_future_mask:
                future_keep_mask = self._compute_future_keep_mask_from_env_state(
                    env_state_obs[:, :n_obs_steps], n_obs_steps=n_obs_steps, dtype=state_obs.dtype
                )
            else:
                non_kalman_feats.append(env_state_obs[:, :n_obs_steps])

        history_gate_context = torch.cat(non_kalman_feats, dim=-1).flatten(start_dim=1)

        future_cond = self._prepare_future_conditioning(
            batch=batch,
            batch_size=batch_size,
            dtype=state_obs.dtype,
            device=state_obs.device,
            state_history_obs=state_obs,
            future_state_obs=future_state_obs,
            history_gate_context=history_gate_context,
            future_keep_mask=future_keep_mask,
        )

        non_kalman_cond = history_gate_context
        if future_cond is not None:
            non_kalman_cond = torch.cat([non_kalman_cond, future_cond], dim=-1)
        if kalman_features is None:
            return non_kalman_cond, None

        full_cond = torch.cat([torch.cat(non_kalman_feats, dim=-1), kalman_features], dim=-1).flatten(
            start_dim=1
        )
        if future_cond is not None:
            full_cond = torch.cat([full_cond, future_cond], dim=-1)
        if self.config.enable_kalman_mid_only_condition:
            return non_kalman_cond, full_cond
        return full_cond, None

    def _prepare_global_conditioning(self, batch: dict[str, Tensor]) -> Tensor:
        """Backward-compatible full global conditioning tensor."""
        global_cond, global_cond_mid = self._prepare_unet_conditioning(batch)
        return global_cond_mid if global_cond_mid is not None else global_cond

    def _compute_online_kalman_from_state(self, batch: dict[str, Tensor]) -> Tensor:
        """
        Compute Kalman features from observation.state on the fly.
        Returns (B, S, D):
          - full10: [pos(3), vel(3), pred_exec(3), valid(1)]
          - posvel6: [pos(3), vel(3)]
          - vel3: [vel(3)]
          - velpred6: [vel(3), pred_exec(3)]
          - pred3: [pred_exec(3)]
        """
        state_obs, _ = self._split_state_sequence(batch[OBS_STATE])
        b, s, _ = state_obs.shape
        z = state_obs[..., self._kalman_pos_slice]
        if z.shape[-1] != 3:
            raise ValueError(
                f"Kalman state position slice {self.config.kalman_state_pos_slice} produced shape {tuple(z.shape)} "
                f"from observation.state shape {tuple(state_obs.shape)}."
            )
        device = state_obs.device
        dtype = state_obs.dtype

        valid = torch.isfinite(z).all(dim=-1)
        z = torch.nan_to_num(z, nan=0.0, posinf=0.0, neginf=0.0)

        dt = self._resolve_kalman_dt(batch, b, s, device=device, dtype=dtype)

        def _make_f_q(step_dt: Tensor) -> tuple[Tensor, Tensor]:
            step_dt = step_dt.to(dtype=dtype)
            dt2 = step_dt.square()
            dt3 = dt2 * step_dt
            dt4 = dt2.square()

            f = torch.eye(6, device=device, dtype=dtype).unsqueeze(0).repeat(b, 1, 1)
            f[:, :3, 3:] = torch.eye(3, device=device, dtype=dtype).unsqueeze(0) * step_dt.view(b, 1, 1)

            sigma2 = float(self.config.kalman_accel_noise_std**2)
            q = torch.zeros((b, 6, 6), device=device, dtype=dtype)
            q_pos = (dt4 / 4.0) * sigma2
            q_cross = (dt3 / 2.0) * sigma2
            q_vel = dt2 * sigma2
            for axis in range(3):
                q[:, axis, axis] = q_pos
                q[:, axis, axis + 3] = q_cross
                q[:, axis + 3, axis] = q_cross
                q[:, axis + 3, axis + 3] = q_vel
            return f, q

        x = torch.zeros((b, 6), device=device, dtype=dtype)
        x[:, :3] = z[:, 0]
        p = torch.zeros((b, 6, 6), device=device, dtype=dtype)
        p_pos = float(self.config.kalman_init_pos_std**2)
        p_vel = float(self.config.kalman_init_vel_std**2)
        for axis in range(3):
            p[:, axis, axis] = p_pos
            p[:, axis + 3, axis + 3] = p_vel

        h = torch.zeros((1, 3, 6), device=device, dtype=dtype).repeat(b, 1, 1)
        h[:, :, :3] = torch.eye(3, device=device, dtype=dtype).unsqueeze(0)
        r = torch.eye(3, device=device, dtype=dtype).unsqueeze(0).repeat(b, 1, 1) * float(
            self.config.kalman_meas_noise_std**2
        )
        i6 = torch.eye(6, device=device, dtype=dtype).unsqueeze(0).repeat(b, 1, 1)

        mode = self.config.kalman_feature_mode
        out = torch.zeros((b, s, self._kalman_feature_dim(mode)), device=device, dtype=dtype)

        for si in range(s):
            if si > 0:
                f, q = _make_f_q(dt[:, si])
                x = torch.bmm(f, x.unsqueeze(-1)).squeeze(-1)
                p = torch.bmm(torch.bmm(f, p), f.transpose(1, 2)) + q

            z_si = z[:, si]
            valid_si = valid[:, si]
            if bool(valid_si.any()):
                y = z_si - torch.bmm(h, x.unsqueeze(-1)).squeeze(-1)
                s_mat = torch.bmm(torch.bmm(h, p), h.transpose(1, 2)) + r
                k_gain = torch.bmm(torch.bmm(p, h.transpose(1, 2)), torch.linalg.inv(s_mat))
                x_upd = x + torch.bmm(k_gain, y.unsqueeze(-1)).squeeze(-1)
                p_upd = torch.bmm(i6 - torch.bmm(k_gain, h), p)
                mask = valid_si.unsqueeze(-1)
                x = torch.where(mask, x_upd, x)
                p = torch.where(mask.unsqueeze(-1), p_upd, p)

            pos = x[:, :3]
            vel = x[:, 3:]
            if mode == "full10":
                out[:, si, :3] = pos
                out[:, si, 3:6] = vel
                f_exec, _ = _make_f_q(
                    torch.full((b,), float(self.config.kalman_predict_horizon), device=device, dtype=dtype)
                )
                x_exec = torch.bmm(f_exec, x.unsqueeze(-1)).squeeze(-1)
                out[:, si, 6:9] = x_exec[:, :3]
                out[:, si, 9] = valid_si.to(dtype=dtype)
            elif mode == "posvel6":
                out[:, si, :3] = pos
                out[:, si, 3:6] = vel
            elif mode == "vel3":
                out[:, si, :3] = vel
            elif mode == "velpred6":
                out[:, si, :3] = vel
                f_exec, _ = _make_f_q(
                    torch.full((b,), float(self.config.kalman_predict_horizon), device=device, dtype=dtype)
                )
                x_exec = torch.bmm(f_exec, x.unsqueeze(-1)).squeeze(-1)
                out[:, si, 3:6] = x_exec[:, :3]
            elif mode == "pred3":
                f_exec, _ = _make_f_q(
                    torch.full((b,), float(self.config.kalman_predict_horizon), device=device, dtype=dtype)
                )
                x_exec = torch.bmm(f_exec, x.unsqueeze(-1)).squeeze(-1)
                out[:, si, :3] = x_exec[:, :3]
            else:
                raise ValueError(f"Unsupported kalman_feature_mode: {mode}")

        return out

    def generate_actions(self, batch: dict[str, Tensor], noise: Tensor | None = None) -> Tensor:
        """
        This function expects `batch` to have:
        {
            "observation.state": (B, n_obs_steps, state_dim)

            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, n_obs_steps, environment_dim)
        }
        """
        batch_size = batch[OBS_STATE].shape[0]
        assert batch[OBS_STATE].shape[1] >= self.config.n_obs_steps

        # Encode image features and concatenate them all together along with the state vector.
        global_cond, global_cond_mid = self._prepare_unet_conditioning(batch)

        # run sampling
        actions = self.conditional_sample(
            batch_size,
            global_cond=global_cond,
            global_cond_mid=global_cond_mid,
            noise=noise,
        )

        # Extract `n_action_steps` steps worth of actions (from the current observation).
        start = self.config.n_obs_steps - 1
        end = start + self.config.n_action_steps
        actions = actions[:, start:end]

        return actions

    def compute_loss(self, batch: dict[str, Tensor]) -> Tensor:
        """
        This function expects `batch` to have (at least):
        {
            "observation.state": (B, n_obs_steps, state_dim)

            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, n_obs_steps, environment_dim)

            "action": (B, horizon, action_dim)
            "action_is_pad": (B, horizon)
        }
        """
        # Input validation.
        assert set(batch).issuperset({OBS_STATE, ACTION, "action_is_pad"})
        assert OBS_IMAGES in batch or OBS_ENV_STATE in batch
        horizon = batch[ACTION].shape[1]
        assert horizon == self.config.horizon
        assert batch[OBS_STATE].shape[1] >= self.config.n_obs_steps

        # Encode image features and concatenate them all together along with the state vector.
        global_cond, global_cond_mid = self._prepare_unet_conditioning(batch)

        # Forward diffusion.
        trajectory = batch[ACTION]
        # Sample noise to add to the trajectory.
        eps = torch.randn(trajectory.shape, device=trajectory.device)
        # Sample a random noising timestep for each item in the batch.
        timesteps = torch.randint(
            low=0,
            high=self.noise_scheduler.config.num_train_timesteps,
            size=(trajectory.shape[0],),
            device=trajectory.device,
        ).long()
        # Add noise to the clean trajectories according to the noise magnitude at each timestep.
        noisy_trajectory = self.noise_scheduler.add_noise(trajectory, eps, timesteps)

        # Run the denoising network (that might denoise the trajectory, or attempt to predict the noise).
        pred = self.unet(
            noisy_trajectory,
            timesteps,
            global_cond=global_cond,
            global_cond_mid=global_cond_mid,
        )

        # Compute the loss.
        # The target is either the original trajectory, or the noise.
        if self.config.prediction_type == "epsilon":
            target = eps
        elif self.config.prediction_type == "sample":
            target = batch[ACTION]
        else:
            raise ValueError(f"Unsupported prediction type {self.config.prediction_type}")

        loss = F.mse_loss(pred, target, reduction="none")

        # Mask loss wherever the action is padded with copies (edges of the dataset trajectory).
        if self.config.do_mask_loss_for_padding:
            if "action_is_pad" not in batch:
                raise ValueError(
                    "You need to provide 'action_is_pad' in the batch when "
                    f"{self.config.do_mask_loss_for_padding=}."
                )
            in_episode_bound = ~batch["action_is_pad"]
            loss = loss * in_episode_bound.unsqueeze(-1)

        return loss.mean()


class SpatialSoftmax(nn.Module):
    """
    Spatial Soft Argmax operation described in "Deep Spatial Autoencoders for Visuomotor Learning" by Finn et al.
    (https://huggingface.co/papers/1509.06113). A minimal port of the robomimic implementation.

    At a high level, this takes 2D feature maps (from a convnet/ViT) and returns the "center of mass"
    of activations of each channel, i.e., keypoints in the image space for the policy to focus on.

    Example: take feature maps of size (512x10x12). We generate a grid of normalized coordinates (10x12x2):
    -----------------------------------------------------
    | (-1., -1.)   | (-0.82, -1.)   | ... | (1., -1.)   |
    | (-1., -0.78) | (-0.82, -0.78) | ... | (1., -0.78) |
    | ...          | ...            | ... | ...         |
    | (-1., 1.)    | (-0.82, 1.)    | ... | (1., 1.)    |
    -----------------------------------------------------
    This is achieved by applying channel-wise softmax over the activations (512x120) and computing the dot
    product with the coordinates (120x2) to get expected points of maximal activation (512x2).

    The example above results in 512 keypoints (corresponding to the 512 input channels). We can optionally
    provide num_kp != None to control the number of keypoints. This is achieved by a first applying a learnable
    linear mapping (in_channels, H, W) -> (num_kp, H, W).
    """

    def __init__(self, input_shape, num_kp=None):
        """
        Args:
            input_shape (list): (C, H, W) input feature map shape.
            num_kp (int): number of keypoints in output. If None, output will have the same number of channels as input.
        """
        super().__init__()

        assert len(input_shape) == 3
        self._in_c, self._in_h, self._in_w = input_shape

        if num_kp is not None:
            self.nets = torch.nn.Conv2d(self._in_c, num_kp, kernel_size=1)
            self._out_c = num_kp
        else:
            self.nets = None
            self._out_c = self._in_c

        # we could use torch.linspace directly but that seems to behave slightly differently than numpy
        # and causes a small degradation in pc_success of pre-trained models.
        pos_x, pos_y = np.meshgrid(np.linspace(-1.0, 1.0, self._in_w), np.linspace(-1.0, 1.0, self._in_h))
        pos_x = torch.from_numpy(pos_x.reshape(self._in_h * self._in_w, 1)).float()
        pos_y = torch.from_numpy(pos_y.reshape(self._in_h * self._in_w, 1)).float()
        # register as buffer so it's moved to the correct device.
        self.register_buffer("pos_grid", torch.cat([pos_x, pos_y], dim=1))

    def forward(self, features: Tensor) -> Tensor:
        """
        Args:
            features: (B, C, H, W) input feature maps.
        Returns:
            (B, K, 2) image-space coordinates of keypoints.
        """
        if self.nets is not None:
            features = self.nets(features)

        # [B, K, H, W] -> [B * K, H * W] where K is number of keypoints
        features = features.reshape(-1, self._in_h * self._in_w)
        # 2d softmax normalization
        attention = F.softmax(features, dim=-1)
        # [B * K, H * W] x [H * W, 2] -> [B * K, 2] for spatial coordinate mean in x and y dimensions
        expected_xy = attention @ self.pos_grid
        # reshape to [B, K, 2]
        feature_keypoints = expected_xy.view(-1, self._out_c, 2)

        return feature_keypoints


class DiffusionRgbEncoder(nn.Module):
    """Encodes an RGB image into a 1D feature vector.

    Includes the ability to normalize and crop the image first.
    """

    def __init__(self, config: DiffusionConfig):
        super().__init__()
        # Set up optional preprocessing.
        if config.resize_shape is not None:
            self.resize = torchvision.transforms.Resize(config.resize_shape)
        else:
            self.resize = None

        crop_shape = config.crop_shape
        if crop_shape is not None:
            self.do_crop = True
            # Always use center crop for eval
            self.center_crop = torchvision.transforms.CenterCrop(crop_shape)
            if config.crop_is_random:
                self.maybe_random_crop = torchvision.transforms.RandomCrop(crop_shape)
            else:
                self.maybe_random_crop = self.center_crop
        else:
            self.do_crop = False

        # Set up backbone.
        backbone_model = getattr(torchvision.models, config.vision_backbone)(
            weights=config.pretrained_backbone_weights
        )
        # Note: This assumes that the layer4 feature map is children()[-3]
        # TODO(alexander-soare): Use a safer alternative.
        self.backbone = nn.Sequential(*(list(backbone_model.children())[:-2]))
        if config.use_group_norm:
            if config.pretrained_backbone_weights:
                raise ValueError(
                    "You can't replace BatchNorm in a pretrained model without ruining the weights!"
                )
            self.backbone = _replace_submodules(
                root_module=self.backbone,
                predicate=lambda x: isinstance(x, nn.BatchNorm2d),
                func=lambda x: nn.GroupNorm(num_groups=x.num_features // 16, num_channels=x.num_features),
            )

        # Set up pooling and final layers.
        # Use a dry run to get the feature map shape.
        # The dummy shape mirrors the runtime preprocessing order: resize -> crop.

        # Note: we have a check in the config class to make sure all images have the same shape.
        images_shape = next(iter(config.image_features.values())).shape
        if config.crop_shape is not None:
            dummy_shape_h_w = config.crop_shape
        elif config.resize_shape is not None:
            dummy_shape_h_w = config.resize_shape
        else:
            dummy_shape_h_w = images_shape[1:]
        dummy_shape = (1, images_shape[0], *dummy_shape_h_w)
        feature_map_shape = get_output_shape(self.backbone, dummy_shape)[1:]

        self.pool = SpatialSoftmax(feature_map_shape, num_kp=config.spatial_softmax_num_keypoints)
        self.feature_dim = config.spatial_softmax_num_keypoints * 2
        self.out = nn.Linear(config.spatial_softmax_num_keypoints * 2, self.feature_dim)
        self.relu = nn.ReLU()

    def forward(self, x: Tensor) -> Tensor:
        """
        Args:
            x: (B, C, H, W) image tensor with pixel values in [0, 1].
        Returns:
            (B, D) image feature.
        """
        # Preprocess: resize if configured, then crop if configured.

        if self.resize is not None:
            x = self.resize(x)
        if self.do_crop:
            if self.training:  # noqa: SIM108
                x = self.maybe_random_crop(x)
            else:
                # Always use center crop for eval.
                x = self.center_crop(x)
        # Extract backbone feature.
        x = torch.flatten(self.pool(self.backbone(x)), start_dim=1)
        # Final linear layer with non-linearity.
        x = self.relu(self.out(x))
        return x


def _replace_submodules(
    root_module: nn.Module, predicate: Callable[[nn.Module], bool], func: Callable[[nn.Module], nn.Module]
) -> nn.Module:
    """
    Args:
        root_module: The module for which the submodules need to be replaced
        predicate: Takes a module as an argument and must return True if the that module is to be replaced.
        func: Takes a module as an argument and returns a new module to replace it with.
    Returns:
        The root module with its submodules replaced.
    """
    if predicate(root_module):
        return func(root_module)

    replace_list = [k.split(".") for k, m in root_module.named_modules(remove_duplicate=True) if predicate(m)]
    for *parents, k in replace_list:
        parent_module = root_module
        if len(parents) > 0:
            parent_module = root_module.get_submodule(".".join(parents))
        if isinstance(parent_module, nn.Sequential):
            src_module = parent_module[int(k)]
        else:
            src_module = getattr(parent_module, k)
        tgt_module = func(src_module)
        if isinstance(parent_module, nn.Sequential):
            parent_module[int(k)] = tgt_module
        else:
            setattr(parent_module, k, tgt_module)
    # verify that all BN are replaced
    assert not any(predicate(m) for _, m in root_module.named_modules(remove_duplicate=True))
    return root_module


class DiffusionSinusoidalPosEmb(nn.Module):
    """1D sinusoidal positional embeddings as in Attention is All You Need."""

    def __init__(self, dim: int):
        super().__init__()
        self.dim = dim

    def forward(self, x: Tensor) -> Tensor:
        device = x.device
        half_dim = self.dim // 2
        emb = math.log(10000) / (half_dim - 1)
        emb = torch.exp(torch.arange(half_dim, device=device) * -emb)
        emb = x.unsqueeze(-1) * emb.unsqueeze(0)
        emb = torch.cat((emb.sin(), emb.cos()), dim=-1)
        return emb


class DiffusionConv1dBlock(nn.Module):
    """Conv1d --> GroupNorm --> Mish"""

    def __init__(self, inp_channels, out_channels, kernel_size, n_groups=8):
        super().__init__()

        self.block = nn.Sequential(
            nn.Conv1d(inp_channels, out_channels, kernel_size, padding=kernel_size // 2),
            nn.GroupNorm(n_groups, out_channels),
            nn.Mish(),
        )

    def forward(self, x):
        return self.block(x)


class DiffusionConditionalUnet1d(nn.Module):
    """A 1D convolutional UNet with FiLM modulation for conditioning.

    Note: this removes local conditioning as compared to the original diffusion policy code.
    """

    def __init__(self, config: DiffusionConfig, global_cond_dim: int, global_cond_mid_dim: int | None = None):
        super().__init__()

        self.config = config

        # Encoder for the diffusion timestep.
        self.diffusion_step_encoder = nn.Sequential(
            DiffusionSinusoidalPosEmb(config.diffusion_step_embed_dim),
            nn.Linear(config.diffusion_step_embed_dim, config.diffusion_step_embed_dim * 4),
            nn.Mish(),
            nn.Linear(config.diffusion_step_embed_dim * 4, config.diffusion_step_embed_dim),
        )

        # FiLM conditioning dimensions.
        cond_dim = config.diffusion_step_embed_dim + global_cond_dim
        mid_cond_dim = (
            config.diffusion_step_embed_dim + global_cond_mid_dim if global_cond_mid_dim is not None else cond_dim
        )

        # In channels / out channels for each downsampling block in the Unet's encoder. For the decoder, we
        # just reverse these.
        in_out = [(config.action_feature.shape[0], config.down_dims[0])] + list(
            zip(config.down_dims[:-1], config.down_dims[1:], strict=True)
        )

        # Unet encoder.
        common_res_block_kwargs = {
            "cond_dim": cond_dim,
            "kernel_size": config.kernel_size,
            "n_groups": config.n_groups,
            "use_film_scale_modulation": config.use_film_scale_modulation,
        }
        mid_res_block_kwargs = {
            "cond_dim": mid_cond_dim,
            "kernel_size": config.kernel_size,
            "n_groups": config.n_groups,
            "use_film_scale_modulation": config.use_film_scale_modulation,
        }
        self.down_modules = nn.ModuleList([])
        for ind, (dim_in, dim_out) in enumerate(in_out):
            is_last = ind >= (len(in_out) - 1)
            self.down_modules.append(
                nn.ModuleList(
                    [
                        DiffusionConditionalResidualBlock1d(dim_in, dim_out, **common_res_block_kwargs),
                        DiffusionConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Downsample as long as it is not the last block.
                        nn.Conv1d(dim_out, dim_out, 3, 2, 1) if not is_last else nn.Identity(),
                    ]
                )
            )

        # Processing in the middle of the auto-encoder.
        self.mid_modules = nn.ModuleList(
            [
                DiffusionConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **mid_res_block_kwargs
                ),
                DiffusionConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **mid_res_block_kwargs
                ),
            ]
        )

        # Unet decoder.
        self.up_modules = nn.ModuleList([])
        for ind, (dim_out, dim_in) in enumerate(reversed(in_out[1:])):
            is_last = ind >= (len(in_out) - 1)
            self.up_modules.append(
                nn.ModuleList(
                    [
                        # dim_in * 2, because it takes the encoder's skip connection as well
                        DiffusionConditionalResidualBlock1d(dim_in * 2, dim_out, **common_res_block_kwargs),
                        DiffusionConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Upsample as long as it is not the last block.
                        nn.ConvTranspose1d(dim_out, dim_out, 4, 2, 1) if not is_last else nn.Identity(),
                    ]
                )
            )

        self.final_conv = nn.Sequential(
            DiffusionConv1dBlock(config.down_dims[0], config.down_dims[0], kernel_size=config.kernel_size),
            nn.Conv1d(config.down_dims[0], config.action_feature.shape[0], 1),
        )

    def forward(
        self,
        x: Tensor,
        timestep: Tensor | int,
        global_cond: Tensor | None = None,
        global_cond_mid: Tensor | None = None,
    ) -> Tensor:
        """
        Args:
            x: (B, T, input_dim) tensor for input to the Unet.
            timestep: (B,) tensor of (timestep_we_are_denoising_from - 1).
            global_cond: (B, global_cond_dim), used by down/up blocks (and mid too when global_cond_mid is None)
            global_cond_mid: (B, global_cond_mid_dim), optional conditioning used only by mid blocks.
            output: (B, T, input_dim)
        Returns:
            (B, T, input_dim) diffusion model prediction.
        """
        # For 1D convolutions we'll need feature dimension first.
        x = einops.rearrange(x, "b t d -> b d t")

        timesteps_embed = self.diffusion_step_encoder(timestep)

        # If there is a global conditioning feature, concatenate it to the timestep embedding.
        if global_cond is not None:
            global_feature = torch.cat([timesteps_embed, global_cond], axis=-1)
        else:
            global_feature = timesteps_embed
        if global_cond_mid is not None:
            mid_global_feature = torch.cat([timesteps_embed, global_cond_mid], axis=-1)
        else:
            mid_global_feature = global_feature

        # Run encoder, keeping track of skip features to pass to the decoder.
        encoder_skip_features: list[Tensor] = []
        for resnet, resnet2, downsample in self.down_modules:
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            encoder_skip_features.append(x)
            x = downsample(x)

        for mid_module in self.mid_modules:
            x = mid_module(x, mid_global_feature)

        # Run decoder, using the skip features from the encoder.
        for resnet, resnet2, upsample in self.up_modules:
            x = torch.cat((x, encoder_skip_features.pop()), dim=1)
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            x = upsample(x)

        x = self.final_conv(x)

        x = einops.rearrange(x, "b d t -> b t d")
        return x


class DiffusionConditionalResidualBlock1d(nn.Module):
    """ResNet style 1D convolutional block with FiLM modulation for conditioning."""

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        cond_dim: int,
        kernel_size: int = 3,
        n_groups: int = 8,
        # Set to True to do scale modulation with FiLM as well as bias modulation (defaults to False meaning
        # FiLM just modulates bias).
        use_film_scale_modulation: bool = False,
    ):
        super().__init__()

        self.use_film_scale_modulation = use_film_scale_modulation
        self.out_channels = out_channels

        self.conv1 = DiffusionConv1dBlock(in_channels, out_channels, kernel_size, n_groups=n_groups)

        # FiLM modulation (https://huggingface.co/papers/1709.07871) outputs per-channel bias and (maybe) scale.
        cond_channels = out_channels * 2 if use_film_scale_modulation else out_channels
        self.cond_encoder = nn.Sequential(nn.Mish(), nn.Linear(cond_dim, cond_channels))

        self.conv2 = DiffusionConv1dBlock(out_channels, out_channels, kernel_size, n_groups=n_groups)

        # A final convolution for dimension matching the residual (if needed).
        self.residual_conv = (
            nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels else nn.Identity()
        )

    def forward(self, x: Tensor, cond: Tensor) -> Tensor:
        """
        Args:
            x: (B, in_channels, T)
            cond: (B, cond_dim)
        Returns:
            (B, out_channels, T)
        """
        out = self.conv1(x)

        # Get condition embedding. Unsqueeze for broadcasting to `out`, resulting in (B, out_channels, 1).
        cond_embed = self.cond_encoder(cond).unsqueeze(-1)
        if self.use_film_scale_modulation:
            # Treat the embedding as a list of scales and biases.
            scale = cond_embed[:, : self.out_channels]
            bias = cond_embed[:, self.out_channels :]
            out = scale * out + bias
        else:
            # Treat the embedding as biases.
            out = out + cond_embed

        out = self.conv2(out)
        out = out + self.residual_conv(x)
        return out
